[project]
name = "debug-panel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.13.7",
]
